CREATE COLUMN TABLE "YOURSCHEMA"."EIP_RA.EIP_RA_USR.SDP_D" ("WID" NVARCHAR(10), "UDC_ID" NVARCHAR(22)) UNLOAD PRIORITY 5  AUTO MERGE ;
COMMENT ON COLUMN "YOURSCHEMA"."EIP_RA.EIP_RA_USR.SDP_D"."WID" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."EIP_RA.EIP_RA_USR.SDP_D"."UDC_ID" is ' '